image: samueldebruyn/debian-git
clone:
  depth: full
pipelines:
  default:
    #- step:
        #name: Deploy to Trinity
        #script:
        #  - apt-get update
        #  - apt-get -qq install git-ftp
        #  - git config git-ftp.url ftp://v3.illuxi.com/public_html/
        #  - git config git-ftp.user $FTP_USERNAME
        #  - git config git-ftp.password $FTP_PASSWORD
        #  #- git ftp push -v
        #  #- git ftp init
        #  - git ftp catchup

    - step:
        # set HEROKU_API_KEY and HEROKU_APP_NAME environment variables
        # set clone `depth: full' as described here: https://confluence.atlassian.com/x/Y9-5Mw
        name: Deploy to Heroku
        # trigger: manual  # uncomment to have a manual step
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master